apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-tracking-app
spec:
  selector:
    matchLabels:
      role: lb-tracking-app
  template:
    metadata:
      labels:
        role: lb-tracking-app
    spec:
      containers:
        - name: lb-tracking-app
          image: jmoyano275/tracking-demo-app:latest
          env:
            - name: TRACKING_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secret-tracking
                  key: mongo-uri
            - name: TRACKING_APP_PORT
              value: "8081"
            - name: TRACKING_RABBIT_URI
              valueFrom:
                secretKeyRef:
                  name: secret-tracking
                  key: rabbit-uri
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: lb-tracking-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32081
  selector:
    role: lb-tracking-app
