apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-inventory-statefulset
spec:
  serviceName: mongodb-inventory
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-inventory
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-inventory
                  key: mongo-password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-inventory-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-inventory-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-inv-svc
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017