apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-tracking-stateful
spec:
  serviceName: mongodb-tracking
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-tracking
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-tracking
                  key: mongo-password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-tra-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-tra-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-tra-svc
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27117
      targetPort: 27017