apiVersion: v1
kind: Secret
metadata:
  name: secret-inventory
type: Opaque
data:
  mongo-username: YWRtaW4=
  mongo-password: YWRtaW4=
  mongo-uri: bW9uZ29kYjovL2FkbWluOmFkbWluQG1vbmdvZGItaW52LXN2YzoyNzAxNy9hZG1pbg==
#  'mongodb://admin:admin@mongodb-inv-svc:27017/admin'
  rabbit-uri: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXNlcnZpY2U6NTY3Mg==
#   'amqp://guest:guest@rabbitmq-service:5672'